name: 'pipeline_analytics'
version: '1.0.0'

profile: 'pipeline_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pipeline_analytics:
    staging:
      +materialized: table
      +schema: staged
      +partition_by:
        field: competencia
        data_type: date
    marts:
      +materialized: table
      +schema: marts
      +partition_by:
        field: competenciadbt
        data_type: date
      +cluster_by:
        - SERVICO
        - CONVENIO
        - COR_CLASSIF

seeds: 
  pipeline_analytics:
    dim_leitos:
      +delimiter: ";"
