pipeline_analytics:
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: pipeline-analytics-emergencia
      dataset: staged
      location: southamerica-east1
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
  target: prod